// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Monitor.Outputs
{

    [OutputType]
    public sealed class DashboardPanelQuery
    {
        /// <summary>
        /// The PromQL query. Must be a valid PromQL query with existing
        /// metrics in Sysdig Monitor.
        /// </summary>
        public readonly string Promql;
        /// <summary>
        /// The type of metric for this query. Can be one of: `percent`, `data`, `data rate`, 
        /// `number`, `number rate`, `time`.
        /// </summary>
        public readonly string Unit;

        [OutputConstructor]
        private DashboardPanelQuery(
            string promql,

            string unit)
        {
            Promql = promql;
            Unit = unit;
        }
    }
}
