// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Monitor.Outputs
{

    [OutputType]
    public sealed class GroupOutlierCapture
    {
        public readonly int Duration;
        public readonly string Filename;
        public readonly string? Filter;

        [OutputConstructor]
        private GroupOutlierCapture(
            int duration,

            string filename,

            string? filter)
        {
            Duration = duration;
            Filename = filename;
            Filter = filter;
        }
    }
}
