// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Monitor.Outputs
{

    [OutputType]
    public sealed class GroupOutlierCustomNotification
    {
        public readonly string? Append;
        public readonly string? Prepend;
        public readonly string Title;

        [OutputConstructor]
        private GroupOutlierCustomNotification(
            string? append,

            string? prepend,

            string title)
        {
            Append = append;
            Prepend = prepend;
            Title = title;
        }
    }
}
