// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Monitor
{
    [SysdigResourceType("sysdig:Monitor/team:Team")]
    public partial class Team : Pulumi.CustomResource
    {
        [Output("canSeeInfrastructureEvents")]
        public Output<bool?> CanSeeInfrastructureEvents { get; private set; } = null!;

        [Output("canUseAwsData")]
        public Output<bool?> CanUseAwsData { get; private set; } = null!;

        [Output("canUseSysdigCapture")]
        public Output<bool?> CanUseSysdigCapture { get; private set; } = null!;

        [Output("defaultTeam")]
        public Output<bool?> DefaultTeam { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("entrypoints")]
        public Output<ImmutableArray<Outputs.TeamEntrypoint>> Entrypoints { get; private set; } = null!;

        [Output("filter")]
        public Output<string?> Filter { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("scopeBy")]
        public Output<string?> ScopeBy { get; private set; } = null!;

        [Output("theme")]
        public Output<string?> Theme { get; private set; } = null!;

        [Output("userRoles")]
        public Output<ImmutableArray<Outputs.TeamUserRole>> UserRoles { get; private set; } = null!;

        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Team resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Team(string name, TeamArgs args, CustomResourceOptions? options = null)
            : base("sysdig:Monitor/team:Team", name, args ?? new TeamArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Team(string name, Input<string> id, TeamState? state = null, CustomResourceOptions? options = null)
            : base("sysdig:Monitor/team:Team", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Team resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Team Get(string name, Input<string> id, TeamState? state = null, CustomResourceOptions? options = null)
        {
            return new Team(name, id, state, options);
        }
    }

    public sealed class TeamArgs : Pulumi.ResourceArgs
    {
        [Input("canSeeInfrastructureEvents")]
        public Input<bool>? CanSeeInfrastructureEvents { get; set; }

        [Input("canUseAwsData")]
        public Input<bool>? CanUseAwsData { get; set; }

        [Input("canUseSysdigCapture")]
        public Input<bool>? CanUseSysdigCapture { get; set; }

        [Input("defaultTeam")]
        public Input<bool>? DefaultTeam { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("entrypoints", required: true)]
        private InputList<Inputs.TeamEntrypointArgs>? _entrypoints;
        public InputList<Inputs.TeamEntrypointArgs> Entrypoints
        {
            get => _entrypoints ?? (_entrypoints = new InputList<Inputs.TeamEntrypointArgs>());
            set => _entrypoints = value;
        }

        [Input("filter")]
        public Input<string>? Filter { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("scopeBy")]
        public Input<string>? ScopeBy { get; set; }

        [Input("theme")]
        public Input<string>? Theme { get; set; }

        [Input("userRoles")]
        private InputList<Inputs.TeamUserRoleArgs>? _userRoles;
        public InputList<Inputs.TeamUserRoleArgs> UserRoles
        {
            get => _userRoles ?? (_userRoles = new InputList<Inputs.TeamUserRoleArgs>());
            set => _userRoles = value;
        }

        public TeamArgs()
        {
        }
    }

    public sealed class TeamState : Pulumi.ResourceArgs
    {
        [Input("canSeeInfrastructureEvents")]
        public Input<bool>? CanSeeInfrastructureEvents { get; set; }

        [Input("canUseAwsData")]
        public Input<bool>? CanUseAwsData { get; set; }

        [Input("canUseSysdigCapture")]
        public Input<bool>? CanUseSysdigCapture { get; set; }

        [Input("defaultTeam")]
        public Input<bool>? DefaultTeam { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("entrypoints")]
        private InputList<Inputs.TeamEntrypointGetArgs>? _entrypoints;
        public InputList<Inputs.TeamEntrypointGetArgs> Entrypoints
        {
            get => _entrypoints ?? (_entrypoints = new InputList<Inputs.TeamEntrypointGetArgs>());
            set => _entrypoints = value;
        }

        [Input("filter")]
        public Input<string>? Filter { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("scopeBy")]
        public Input<string>? ScopeBy { get; set; }

        [Input("theme")]
        public Input<string>? Theme { get; set; }

        [Input("userRoles")]
        private InputList<Inputs.TeamUserRoleGetArgs>? _userRoles;
        public InputList<Inputs.TeamUserRoleGetArgs> UserRoles
        {
            get => _userRoles ?? (_userRoles = new InputList<Inputs.TeamUserRoleGetArgs>());
            set => _userRoles = value;
        }

        [Input("version")]
        public Input<int>? Version { get; set; }

        public TeamState()
        {
        }
    }
}
