// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./benchmarkTask";
export * from "./cloudAccount";
export * from "./getNotificationChannel";
export * from "./getTrustedCloudIdentity";
export * from "./list";
export * from "./macro";
export * from "./notificationChannelEmail";
export * from "./notificationChannelOpsgenie";
export * from "./notificationChannelPagerduty";
export * from "./notificationChannelSlack";
export * from "./notificationChannelSns";
export * from "./notificationChannelVictorops";
export * from "./notificationChannelWebhook";
export * from "./policy";
export * from "./ruleContainer";
export * from "./ruleFalco";
export * from "./ruleFilesystem";
export * from "./ruleNetwork";
export * from "./ruleProcess";
export * from "./ruleSyscall";
export * from "./team";
export * from "./vulnerabilityException";
export * from "./vulnerabilityExceptionList";

// Import resources to register:
import { BenchmarkTask } from "./benchmarkTask";
import { CloudAccount } from "./cloudAccount";
import { List } from "./list";
import { Macro } from "./macro";
import { NotificationChannelEmail } from "./notificationChannelEmail";
import { NotificationChannelOpsgenie } from "./notificationChannelOpsgenie";
import { NotificationChannelPagerduty } from "./notificationChannelPagerduty";
import { NotificationChannelSlack } from "./notificationChannelSlack";
import { NotificationChannelSns } from "./notificationChannelSns";
import { NotificationChannelVictorops } from "./notificationChannelVictorops";
import { NotificationChannelWebhook } from "./notificationChannelWebhook";
import { Policy } from "./policy";
import { RuleContainer } from "./ruleContainer";
import { RuleFalco } from "./ruleFalco";
import { RuleFilesystem } from "./ruleFilesystem";
import { RuleNetwork } from "./ruleNetwork";
import { RuleProcess } from "./ruleProcess";
import { RuleSyscall } from "./ruleSyscall";
import { Team } from "./team";
import { VulnerabilityException } from "./vulnerabilityException";
import { VulnerabilityExceptionList } from "./vulnerabilityExceptionList";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sysdig:Secure/benchmarkTask:BenchmarkTask":
                return new BenchmarkTask(name, <any>undefined, { urn })
            case "sysdig:Secure/cloudAccount:CloudAccount":
                return new CloudAccount(name, <any>undefined, { urn })
            case "sysdig:Secure/list:List":
                return new List(name, <any>undefined, { urn })
            case "sysdig:Secure/macro:Macro":
                return new Macro(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelEmail:NotificationChannelEmail":
                return new NotificationChannelEmail(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelOpsgenie:NotificationChannelOpsgenie":
                return new NotificationChannelOpsgenie(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelPagerduty:NotificationChannelPagerduty":
                return new NotificationChannelPagerduty(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelSlack:NotificationChannelSlack":
                return new NotificationChannelSlack(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelSns:NotificationChannelSns":
                return new NotificationChannelSns(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelVictorops:NotificationChannelVictorops":
                return new NotificationChannelVictorops(name, <any>undefined, { urn })
            case "sysdig:Secure/notificationChannelWebhook:NotificationChannelWebhook":
                return new NotificationChannelWebhook(name, <any>undefined, { urn })
            case "sysdig:Secure/policy:Policy":
                return new Policy(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleContainer:RuleContainer":
                return new RuleContainer(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleFalco:RuleFalco":
                return new RuleFalco(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleFilesystem:RuleFilesystem":
                return new RuleFilesystem(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleNetwork:RuleNetwork":
                return new RuleNetwork(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleProcess:RuleProcess":
                return new RuleProcess(name, <any>undefined, { urn })
            case "sysdig:Secure/ruleSyscall:RuleSyscall":
                return new RuleSyscall(name, <any>undefined, { urn })
            case "sysdig:Secure/team:Team":
                return new Team(name, <any>undefined, { urn })
            case "sysdig:Secure/vulnerabilityException:VulnerabilityException":
                return new VulnerabilityException(name, <any>undefined, { urn })
            case "sysdig:Secure/vulnerabilityExceptionList:VulnerabilityExceptionList":
                return new VulnerabilityExceptionList(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sysdig", "Secure/benchmarkTask", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/cloudAccount", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/list", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/macro", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelEmail", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelOpsgenie", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelPagerduty", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelSlack", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelSns", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelVictorops", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/notificationChannelWebhook", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/policy", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleContainer", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleFalco", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleFilesystem", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleNetwork", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleProcess", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/ruleSyscall", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/team", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/vulnerabilityException", _module)
pulumi.runtime.registerResourceModule("sysdig", "Secure/vulnerabilityExceptionList", _module)
