// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * ## Import
 *
 * Event Monitor alerts can be imported using the alert ID, e.g.
 *
 * ```sh
 *  $ pulumi import sysdig:Monitor/alertEvent:AlertEvent example 12345
 * ```
 */
export class AlertEvent extends pulumi.CustomResource {
    /**
     * Get an existing AlertEvent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertEventState, opts?: pulumi.CustomResourceOptions): AlertEvent {
        return new AlertEvent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sysdig:Monitor/alertEvent:AlertEvent';

    /**
     * Returns true if the given object is an instance of AlertEvent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertEvent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertEvent.__pulumiType;
    }

    /**
     * Enables the creation of a capture file of the syscalls during the event.
     */
    public readonly capture!: pulumi.Output<outputs.Monitor.AlertEventCapture | undefined>;
    /**
     * Allows to define a custom notification title, prepend and append text.
     */
    public readonly customNotification!: pulumi.Output<outputs.Monitor.AlertEventCustomNotification | undefined>;
    /**
     * The description of Monitor alert.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Boolean that defines if the alert is enabled or not. Defaults to true.
     */
    public readonly enabled!: pulumi.Output<boolean | undefined>;
    /**
     * Number of events to match with event_rel.
     */
    public readonly eventCount!: pulumi.Output<number>;
    /**
     * String that matches part of name, tag or the description of Sysdig Events.
     */
    public readonly eventName!: pulumi.Output<string>;
    /**
     * Relationship of the event count. It can be `>`, `>=`, `<`, `<=`, `=` or `!=`.
     */
    public readonly eventRel!: pulumi.Output<string>;
    /**
     * List of segments to trigger a separate alert on. Example: `["kubernetes.cluster.name", "kubernetes.namespace.name"]`.
     */
    public readonly multipleAlertsBies!: pulumi.Output<string[] | undefined>;
    /**
     * The name of the Monitor alert. It must be unique.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * List of notification channel IDs where an alert must be sent to once fired.
     */
    public readonly notificationChannels!: pulumi.Output<number[] | undefined>;
    /**
     * Number of minutes for the alert to re-notify until the status is solved.
     */
    public readonly renotificationMinutes!: pulumi.Output<number | undefined>;
    /**
     * Part of the infrastructure where the alert is valid. Defaults to the entire infrastructure.
     */
    public readonly scope!: pulumi.Output<string | undefined>;
    /**
     * Severity of the Monitor alert. It must be a value between 0 and 7,
     * with 0 being the most critical and 7 the less critical. Defaults to 4.
     */
    public readonly severity!: pulumi.Output<number | undefined>;
    /**
     * Source of the event. It can be `docker` or `kubernetes`.
     */
    public readonly source!: pulumi.Output<string>;
    /**
     * Team ID that owns the alert.
     */
    public /*out*/ readonly team!: pulumi.Output<number>;
    /**
     * Threshold of time for the status to stabilize until the alert is fired.
     */
    public readonly triggerAfterMinutes!: pulumi.Output<number>;
    /**
     * Current version of the resource in Sysdig Monitor.
     */
    public /*out*/ readonly version!: pulumi.Output<number>;

    /**
     * Create a AlertEvent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertEventArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertEventArgs | AlertEventState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertEventState | undefined;
            inputs["capture"] = state ? state.capture : undefined;
            inputs["customNotification"] = state ? state.customNotification : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["enabled"] = state ? state.enabled : undefined;
            inputs["eventCount"] = state ? state.eventCount : undefined;
            inputs["eventName"] = state ? state.eventName : undefined;
            inputs["eventRel"] = state ? state.eventRel : undefined;
            inputs["multipleAlertsBies"] = state ? state.multipleAlertsBies : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["notificationChannels"] = state ? state.notificationChannels : undefined;
            inputs["renotificationMinutes"] = state ? state.renotificationMinutes : undefined;
            inputs["scope"] = state ? state.scope : undefined;
            inputs["severity"] = state ? state.severity : undefined;
            inputs["source"] = state ? state.source : undefined;
            inputs["team"] = state ? state.team : undefined;
            inputs["triggerAfterMinutes"] = state ? state.triggerAfterMinutes : undefined;
            inputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as AlertEventArgs | undefined;
            if ((!args || args.eventCount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'eventCount'");
            }
            if ((!args || args.eventName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'eventName'");
            }
            if ((!args || args.eventRel === undefined) && !opts.urn) {
                throw new Error("Missing required property 'eventRel'");
            }
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            if ((!args || args.triggerAfterMinutes === undefined) && !opts.urn) {
                throw new Error("Missing required property 'triggerAfterMinutes'");
            }
            inputs["capture"] = args ? args.capture : undefined;
            inputs["customNotification"] = args ? args.customNotification : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["enabled"] = args ? args.enabled : undefined;
            inputs["eventCount"] = args ? args.eventCount : undefined;
            inputs["eventName"] = args ? args.eventName : undefined;
            inputs["eventRel"] = args ? args.eventRel : undefined;
            inputs["multipleAlertsBies"] = args ? args.multipleAlertsBies : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["notificationChannels"] = args ? args.notificationChannels : undefined;
            inputs["renotificationMinutes"] = args ? args.renotificationMinutes : undefined;
            inputs["scope"] = args ? args.scope : undefined;
            inputs["severity"] = args ? args.severity : undefined;
            inputs["source"] = args ? args.source : undefined;
            inputs["triggerAfterMinutes"] = args ? args.triggerAfterMinutes : undefined;
            inputs["team"] = undefined /*out*/;
            inputs["version"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(AlertEvent.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AlertEvent resources.
 */
export interface AlertEventState {
    /**
     * Enables the creation of a capture file of the syscalls during the event.
     */
    capture?: pulumi.Input<inputs.Monitor.AlertEventCapture>;
    /**
     * Allows to define a custom notification title, prepend and append text.
     */
    customNotification?: pulumi.Input<inputs.Monitor.AlertEventCustomNotification>;
    /**
     * The description of Monitor alert.
     */
    description?: pulumi.Input<string>;
    /**
     * Boolean that defines if the alert is enabled or not. Defaults to true.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Number of events to match with event_rel.
     */
    eventCount?: pulumi.Input<number>;
    /**
     * String that matches part of name, tag or the description of Sysdig Events.
     */
    eventName?: pulumi.Input<string>;
    /**
     * Relationship of the event count. It can be `>`, `>=`, `<`, `<=`, `=` or `!=`.
     */
    eventRel?: pulumi.Input<string>;
    /**
     * List of segments to trigger a separate alert on. Example: `["kubernetes.cluster.name", "kubernetes.namespace.name"]`.
     */
    multipleAlertsBies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the Monitor alert. It must be unique.
     */
    name?: pulumi.Input<string>;
    /**
     * List of notification channel IDs where an alert must be sent to once fired.
     */
    notificationChannels?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Number of minutes for the alert to re-notify until the status is solved.
     */
    renotificationMinutes?: pulumi.Input<number>;
    /**
     * Part of the infrastructure where the alert is valid. Defaults to the entire infrastructure.
     */
    scope?: pulumi.Input<string>;
    /**
     * Severity of the Monitor alert. It must be a value between 0 and 7,
     * with 0 being the most critical and 7 the less critical. Defaults to 4.
     */
    severity?: pulumi.Input<number>;
    /**
     * Source of the event. It can be `docker` or `kubernetes`.
     */
    source?: pulumi.Input<string>;
    /**
     * Team ID that owns the alert.
     */
    team?: pulumi.Input<number>;
    /**
     * Threshold of time for the status to stabilize until the alert is fired.
     */
    triggerAfterMinutes?: pulumi.Input<number>;
    /**
     * Current version of the resource in Sysdig Monitor.
     */
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a AlertEvent resource.
 */
export interface AlertEventArgs {
    /**
     * Enables the creation of a capture file of the syscalls during the event.
     */
    capture?: pulumi.Input<inputs.Monitor.AlertEventCapture>;
    /**
     * Allows to define a custom notification title, prepend and append text.
     */
    customNotification?: pulumi.Input<inputs.Monitor.AlertEventCustomNotification>;
    /**
     * The description of Monitor alert.
     */
    description?: pulumi.Input<string>;
    /**
     * Boolean that defines if the alert is enabled or not. Defaults to true.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Number of events to match with event_rel.
     */
    eventCount: pulumi.Input<number>;
    /**
     * String that matches part of name, tag or the description of Sysdig Events.
     */
    eventName: pulumi.Input<string>;
    /**
     * Relationship of the event count. It can be `>`, `>=`, `<`, `<=`, `=` or `!=`.
     */
    eventRel: pulumi.Input<string>;
    /**
     * List of segments to trigger a separate alert on. Example: `["kubernetes.cluster.name", "kubernetes.namespace.name"]`.
     */
    multipleAlertsBies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the Monitor alert. It must be unique.
     */
    name?: pulumi.Input<string>;
    /**
     * List of notification channel IDs where an alert must be sent to once fired.
     */
    notificationChannels?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Number of minutes for the alert to re-notify until the status is solved.
     */
    renotificationMinutes?: pulumi.Input<number>;
    /**
     * Part of the infrastructure where the alert is valid. Defaults to the entire infrastructure.
     */
    scope?: pulumi.Input<string>;
    /**
     * Severity of the Monitor alert. It must be a value between 0 and 7,
     * with 0 being the most critical and 7 the less critical. Defaults to 4.
     */
    severity?: pulumi.Input<number>;
    /**
     * Source of the event. It can be `docker` or `kubernetes`.
     */
    source: pulumi.Input<string>;
    /**
     * Threshold of time for the status to stabilize until the alert is fired.
     */
    triggerAfterMinutes: pulumi.Input<number>;
}
