// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./alertAnomaly";
export * from "./alertDashboard";
export * from "./alertDowntime";
export * from "./alertEvent";
export * from "./groupOutlier";
export * from "./metric";
export * from "./notificationChannelEmail";
export * from "./notificationChannelOpsgenie";
export * from "./notificationChannelPagerduty";
export * from "./notificationChannelSlack";
export * from "./notificationChannelSns";
export * from "./notificationChannelVictorops";
export * from "./notificationChannelWebhook";
export * from "./promql";
export * from "./team";

// Import resources to register:
import { AlertAnomaly } from "./alertAnomaly";
import { AlertDashboard } from "./alertDashboard";
import { AlertDowntime } from "./alertDowntime";
import { AlertEvent } from "./alertEvent";
import { GroupOutlier } from "./groupOutlier";
import { Metric } from "./metric";
import { NotificationChannelEmail } from "./notificationChannelEmail";
import { NotificationChannelOpsgenie } from "./notificationChannelOpsgenie";
import { NotificationChannelPagerduty } from "./notificationChannelPagerduty";
import { NotificationChannelSlack } from "./notificationChannelSlack";
import { NotificationChannelSns } from "./notificationChannelSns";
import { NotificationChannelVictorops } from "./notificationChannelVictorops";
import { NotificationChannelWebhook } from "./notificationChannelWebhook";
import { Promql } from "./promql";
import { Team } from "./team";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sysdig:Monitor/alertAnomaly:AlertAnomaly":
                return new AlertAnomaly(name, <any>undefined, { urn })
            case "sysdig:Monitor/alertDashboard:AlertDashboard":
                return new AlertDashboard(name, <any>undefined, { urn })
            case "sysdig:Monitor/alertDowntime:AlertDowntime":
                return new AlertDowntime(name, <any>undefined, { urn })
            case "sysdig:Monitor/alertEvent:AlertEvent":
                return new AlertEvent(name, <any>undefined, { urn })
            case "sysdig:Monitor/groupOutlier:GroupOutlier":
                return new GroupOutlier(name, <any>undefined, { urn })
            case "sysdig:Monitor/metric:Metric":
                return new Metric(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelEmail:NotificationChannelEmail":
                return new NotificationChannelEmail(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelOpsgenie:NotificationChannelOpsgenie":
                return new NotificationChannelOpsgenie(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelPagerduty:NotificationChannelPagerduty":
                return new NotificationChannelPagerduty(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelSlack:NotificationChannelSlack":
                return new NotificationChannelSlack(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelSns:NotificationChannelSns":
                return new NotificationChannelSns(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelVictorops:NotificationChannelVictorops":
                return new NotificationChannelVictorops(name, <any>undefined, { urn })
            case "sysdig:Monitor/notificationChannelWebhook:NotificationChannelWebhook":
                return new NotificationChannelWebhook(name, <any>undefined, { urn })
            case "sysdig:Monitor/promql:Promql":
                return new Promql(name, <any>undefined, { urn })
            case "sysdig:Monitor/team:Team":
                return new Team(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sysdig", "Monitor/alertAnomaly", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/alertDashboard", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/alertDowntime", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/alertEvent", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/groupOutlier", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/metric", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelEmail", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelOpsgenie", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelPagerduty", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelSlack", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelSns", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelVictorops", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/notificationChannelWebhook", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/promql", _module)
pulumi.runtime.registerResourceModule("sysdig", "Monitor/team", _module)
