// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Secure.Inputs
{

    public sealed class RuleFalcoExceptionArgs : Pulumi.ResourceArgs
    {
        [Input("comps", required: true)]
        private InputList<string>? _comps;
        public InputList<string> Comps
        {
            get => _comps ?? (_comps = new InputList<string>());
            set => _comps = value;
        }

        [Input("fields", required: true)]
        private InputList<string>? _fields;
        public InputList<string> Fields
        {
            get => _fields ?? (_fields = new InputList<string>());
            set => _fields = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("values", required: true)]
        public Input<string> Values { get; set; } = null!;

        public RuleFalcoExceptionArgs()
        {
        }
    }
}
