// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetExtraHeaders(ctx *pulumi.Context) string {
	return config.Get(ctx, "sysdig:extraHeaders")
}
func GetSysdigMonitorApiToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "sysdig:sysdigMonitorApiToken")
}
func GetSysdigMonitorInsecureTls(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "sysdig:sysdigMonitorInsecureTls")
}
func GetSysdigMonitorUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "sysdig:sysdigMonitorUrl")
}
func GetSysdigSecureApiToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "sysdig:sysdigSecureApiToken")
}
func GetSysdigSecureInsecureTls(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "sysdig:sysdigSecureInsecureTls")
}
func GetSysdigSecureUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "sysdig:sysdigSecureUrl")
}
