// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Monitor.Inputs
{

    public sealed class TeamEntrypointGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Sets up the defined Dashboard name as entrypoint.
        /// Warning: This field must only be added if the `type` is "Dashboards".
        /// </summary>
        [Input("selection")]
        public Input<string>? Selection { get; set; }

        /// <summary>
        /// Main entrypoint for the team.
        /// Valid options are: Explore, Dashboards, Events, Alerts, Settings.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public TeamEntrypointGetArgs()
        {
        }
    }
}
