// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sysdig.Secure
{
    public static class GetTrustedCloudIdentity
    {
        public static Task<GetTrustedCloudIdentityResult> InvokeAsync(GetTrustedCloudIdentityArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTrustedCloudIdentityResult>("sysdig:Secure/getTrustedCloudIdentity:GetTrustedCloudIdentity", args ?? new GetTrustedCloudIdentityArgs(), options.WithVersion());
    }


    public sealed class GetTrustedCloudIdentityArgs : Pulumi.InvokeArgs
    {
        [Input("cloudProvider", required: true)]
        public string CloudProvider { get; set; } = null!;

        public GetTrustedCloudIdentityArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetTrustedCloudIdentityResult
    {
        public readonly string AwsAccountId;
        public readonly string AwsRoleName;
        public readonly string AzureServicePrincipalId;
        public readonly string AzureTenantId;
        public readonly string CloudProvider;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Identity;

        [OutputConstructor]
        private GetTrustedCloudIdentityResult(
            string awsAccountId,

            string awsRoleName,

            string azureServicePrincipalId,

            string azureTenantId,

            string cloudProvider,

            string id,

            string identity)
        {
            AwsAccountId = awsAccountId;
            AwsRoleName = awsRoleName;
            AzureServicePrincipalId = azureServicePrincipalId;
            AzureTenantId = azureTenantId;
            CloudProvider = cloudProvider;
            Id = id;
            Identity = identity;
        }
    }
}
