// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFargateWorkloadAgent(args: GetFargateWorkloadAgentArgs, opts?: pulumi.InvokeOptions): Promise<GetFargateWorkloadAgentResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("sysdig:index/getFargateWorkloadAgent:GetFargateWorkloadAgent", {
        "collectorHost": args.collectorHost,
        "collectorPort": args.collectorPort,
        "containerDefinitions": args.containerDefinitions,
        "imageAuthSecret": args.imageAuthSecret,
        "orchestratorHost": args.orchestratorHost,
        "orchestratorPort": args.orchestratorPort,
        "sysdigAccessKey": args.sysdigAccessKey,
        "workloadAgentImage": args.workloadAgentImage,
    }, opts);
}

/**
 * A collection of arguments for invoking GetFargateWorkloadAgent.
 */
export interface GetFargateWorkloadAgentArgs {
    collectorHost?: string;
    collectorPort?: string;
    containerDefinitions: string;
    imageAuthSecret?: string;
    orchestratorHost?: string;
    orchestratorPort?: string;
    sysdigAccessKey: string;
    workloadAgentImage: string;
}

/**
 * A collection of values returned by GetFargateWorkloadAgent.
 */
export interface GetFargateWorkloadAgentResult {
    readonly collectorHost?: string;
    readonly collectorPort?: string;
    readonly containerDefinitions: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageAuthSecret?: string;
    readonly orchestratorHost?: string;
    readonly orchestratorPort?: string;
    readonly outputContainerDefinitions: string;
    readonly sysdigAccessKey: string;
    readonly workloadAgentImage: string;
}

export function getFargateWorkloadAgentOutput(args: GetFargateWorkloadAgentOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFargateWorkloadAgentResult> {
    return pulumi.output(args).apply(a => getFargateWorkloadAgent(a, opts))
}

/**
 * A collection of arguments for invoking GetFargateWorkloadAgent.
 */
export interface GetFargateWorkloadAgentOutputArgs {
    collectorHost?: pulumi.Input<string>;
    collectorPort?: pulumi.Input<string>;
    containerDefinitions: pulumi.Input<string>;
    imageAuthSecret?: pulumi.Input<string>;
    orchestratorHost?: pulumi.Input<string>;
    orchestratorPort?: pulumi.Input<string>;
    sysdigAccessKey: pulumi.Input<string>;
    workloadAgentImage: pulumi.Input<string>;
}
