// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./currentUser";
export * from "./fargateWorkloadAgent";
export * from "./provider";

// Export sub-modules:
import * as config from "./config";
import * as monitor from "./monitor";
import * as secure from "./secure";
import * as types from "./types";

export {
    config,
    monitor,
    secure,
    types,
};

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("sysdig", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:sysdig") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
